#pragma once

typedef enum {
    FLYWHEEL_STOP, FLYWHEEL_FULL_SPEED,

    DRIVE_LINEAR, DRIVE_ROTATE, DRIVE_STOP_LINEAR, DRIVE_STOP_ROTATE,

    BALL_LIFT_UP, BALL_LIFT_DOWN, BALL_LIFT_STOP,

    CAP_LIFT_UP, CAP_LIFT_DOWN, CAP_LIFT_HOLD, CAP_LIFT_DROP,

    CLAW_ROTATE_180
} ComponentAction;